# Generated by Django 3.1.8 on 2021-11-02 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 16, 55, 56, 963003)),
        ),
    ]
