# Generated by Django 3.1.8 on 2021-11-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211102_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
