# Generated by Django 3.1.8 on 2021-11-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211102_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='AdvisorId',
            new_name='Advisor_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='UserId',
            new_name='User_id',
        ),
    ]
